version: '3'

volumes:
  rabbitmq-data: {}
  redis-data: {}

services:
  rabbit:
    image:
      rabbitmq:3-management
#    ports:
#      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    container_name: rabbitmq
    network_mode: "host"
  redis:
    image:
      redis:7
#    ports:
#      - "6379:6379"
    volumes:
      - redis-data:/data
    container_name: redis
    network_mode: "host"
  redis-commander:
    image:
      rediscommander/redis-commander:latest
#    ports:
#      - "8081:8081"
    volumes:
      - redis-data:/data
    container_name: redis-commander
    network_mode: "host"
  parser:
    image:
      kosbr/content-categorize-page-parser:1a9eaffd560add8297aa59f03c6ddaab22c790a8
    container_name: parser
    network_mode: "host"
   
